name: Pei
favicon: null
layout_spectrum: 0.6112900921143591
typography_spectrum: 0.16285748197697103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.05742122419178486
  lightness: 0.2595678309444338
  saturation: 0.08857078524306417
  rhythmicContrast: 0.36602049483917654
purpose: []
